import type { Metadata } from "next";
import { fonts } from './fonts'
import "./globals.css";
import { Providers } from './providers'

export const metadata: Metadata = {
  title: "ASCENDANT ALLIES",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <body className={fonts.mateSc.variable}>
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
